name: expensetracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1  
  path_provider: ^2.1.2

  firebase_core: ^3.14.0     
  cloud_firestore: ^5.0.0     
  cupertino_icons: ^1.0.8
  http: ^1.1.0     
  flutter_secure_storage: ^9.0.0  
  shared_preferences: ^2.2.2
  lottie: ^3.3.1
  firebase_messaging: ^15.2.7


     

dev_dependencies:

  font_awesome_flutter: ^10.6.0
  flutter_lints: ^5.0.0
  fl_chart: ^1.0.0
  flutter_colorpicker: ^1.1.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

flutter:
  assets:
    - assets/

  uses-material-design: true
