// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmFEjRO0YH1mNf1opt-k256lG3pnHEQNU',
    appId: '1:66674526005:web:c04541f9377acafae52e7c',
    messagingSenderId: '66674526005',
    projectId: 'pushnotification-7da71',
    authDomain: 'pushnotification-7da71.firebaseapp.com',
    storageBucket: 'pushnotification-7da71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGKfp6SJxOXluBL6RwzpENH--88aXfQY',
    appId: '1:66674526005:android:9c29eb27eb7ed695e52e7c',
    messagingSenderId: '66674526005',
    projectId: 'pushnotification-7da71',
    storageBucket: 'pushnotification-7da71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDinoNvARtA4742GxQlgP2WkBCi2X9ERA',
    appId: '1:66674526005:ios:f42f81c339e6b0eee52e7c',
    messagingSenderId: '66674526005',
    projectId: 'pushnotification-7da71',
    storageBucket: 'pushnotification-7da71.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDinoNvARtA4742GxQlgP2WkBCi2X9ERA',
    appId: '1:66674526005:ios:f42f81c339e6b0eee52e7c',
    messagingSenderId: '66674526005',
    projectId: 'pushnotification-7da71',
    storageBucket: 'pushnotification-7da71.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmFEjRO0YH1mNf1opt-k256lG3pnHEQNU',
    appId: '1:66674526005:web:e7ee98aa2e8b652fe52e7c',
    messagingSenderId: '66674526005',
    projectId: 'pushnotification-7da71',
    authDomain: 'pushnotification-7da71.firebaseapp.com',
    storageBucket: 'pushnotification-7da71.firebasestorage.app',
  );
}
